
\connect perime-user-db

  CREATE TABLE "Users"
(
  id integer NULL GENERATED BY DEFAULT AS IDENTITY,
  username text,
  passhash text,
  address text,
  cellphone bigint NOT NULL,
  email text,
  CONSTRAINT "PK_Users" PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "Users"
  OWNER TO postgresuser;
